# This file was generated by GoReleaser. DO NOT EDIT.
cask "grimoire" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "f2b027f3ed29d59479d7321c6192f0d351eced2c0bf8dd954f4469733e6ec699"
      url "https://github.com/jlkendrick/grimoire/releases/download/v#{version}/grimoire_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f09686819f515306b48c762b6402d0bce04613ab608e3911126ed31d283488a"
      url "https://github.com/jlkendrick/grimoire/releases/download/v#{version}/grimoire_darwin_arm64.tar.gz"
    end
  end

  name "grimoire"
  desc "A declarative, language-agnostic execution framework. Write pure functions, describe them in spell.yaml, get a fully typed CLI."
  homepage "https://jlkendrick.github.io/janus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grimoire"

  # No zap stanza required

end
